version: 2.1

executors:
  exe_nodejs:
    docker:
      - image: circleci/node:14.15-browsers

jobs:
  TheSetup:
    steps:
      - checkout
      - run: | 
          echo "npm install"
          npm install
      - persist_to_workspace:
          root: .
          paths: .
  TheTest:
    steps:
      - run:
          name: Run unit tests
          command: npm run test

workflows:
  version: 2
  Name-RunTests:
    jobs:
      - TheSetup
      - TheTest:
          requires:
            - TheSetup