version: 2.1

executors:
  exe_nodejs:
    docker:
      - image: circleci/node:14.15-browsers
    working_directory: ~/repo

jobs:
  TheSetup:
    executor: exe_nodejs
    steps:
      - checkout
      - run: npm install
      - persist_to_workspace:
          root: .
          paths: .
  TheTest:
    executor: exe_nodejs
    steps:
      - run: npm run test

workflows:
  version: 2
  Name-RunTests:
    jobs:
      - TheSetup
      - TheTest:
          requires:
            - TheSetup