version: 2.1

executors:
  exe_nodejs:
    docker:
      - image: circleci/node:14.15-browsers
    working_directory: ~/project

jobs:
  TheSetup:
    executor: exe_nodejs
    steps:
      - checkout
      - run: npm install
  TheTest:
    executor: exe_nodejs
    steps:
      - run:
          command: npm run test

# Orchestrate or schedule a set of jobs
workflows:
  version: 2
  # Name the workflow
  Name-RunTests:
    # Run the welcome/run job in its own container
    jobs:
      - TheSetup
      - TheTest:
          requires:
            - TheSetup