version: 2.1

defaults: &defaults
  docker:
    - image: circleci/node:14.15-browsers

jobs:
  TheSetup:
    <<: *defaults
    steps:
      - checkout
      - run: npm install
      - persist_to_workspace:
          root: .
          paths: .
  TheTest:
    <<: *defaults
    steps:
      - run: npm run test

workflows:
  version: 2
  TheSetupAndTest:
    jobs:
      - TheSetup
      - TheTest:
          requires:
            - TheSetup