version: 2.1

executors:
  exe_nodejs:
    docker:
      - image: circleci/node:14.15-browsers

jobs:
  setup:
    executor: exe_nodejs
    steps:
      - checkout
      - run: | 
          echo "npm install"
          npm install
  test:
    executor: exe_nodejs
    steps:
      - run:
          name: Run unit tests
          command: npm run test

# Orchestrate or schedule a set of jobs
workflows:
  version: 2
  # Name the workflow
  Name-RunTests:
    # Run the welcome/run job in its own container
    jobs:
      - setup