version: 2.1

executors:
  exe_nodejs:
    docker:
      - image: circleci/node:14.15-browsers

jobs:
  TheSetup:
    executor: exe_nodejs
    steps:
      - checkout
      - run:
          command: npm install
  TheTest:
    executor: exe_nodejs
    steps:
      - run:
          name: Run unit tests
          command: npm run test

workflows:
  version: 2
  Name-RunTests:
    jobs:
      - TheSetup
      - TheTest:
          requires:
            - TheSetup